# Generated by Django 5.2.5 on 2025-12-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cricket/')),
            ],
        ),
    ]
