# Generated by Django 5.2.5 on 2025-12-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball', '0002_cricketfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pickleball_court',
            new_name='courts',
        ),
        migrations.DeleteModel(
            name='CricketField',
        ),
    ]
