# Generated by Django 5.2.5 on 2025-12-06 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball', '0003_rename_pickleball_court_courts_delete_cricketfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter a valid 10-digit phone number starting with 6–9')]),
        ),
    ]
